Models/Event.cs
namespace Coding_Events.Models;

public class Event
{
    public string? Name {get; set;}
    public string? Description { get; set; }

    public EventCategory? Category {get; set;}
    public int CategoryId {get;set;}
    public int Id {get; set;}

    public ICollection<Tag>? Tags { get; set; }

    public Event()
    {
    }
    public Event (string name, string description)
    {
        Name = name;
        Description = description;
        Tags = new List<Tag>();
    }

    public override string? ToString()
    {
        return Name;
    }
       public override bool Equals(object? obj)
   {
      return obj is Event @event && Id == @event.Id;
   }

   public override int GetHashCode()
   {
      return HashCode.Combine(Id);
   }
}

Controllers/EventsController.cs
namespace Coding_Events;
using Microsoft.AspNetCore.Mvc;
using Coding_Events.Data;
using Coding_Events.Models;
using Coding_Events.ViewModels;
using Microsoft.EntityFrameworkCore;

public class EventsController : Controller
{
    private EventDbContext context;

    public EventsController(EventDbContext dbContext)
    {
        context = dbContext;
    }


    // GET: <port>/events
    [HttpGet]
    public IActionResult Index() 
    {
        List<Event> events = context.Events.Include(e=>e.Category).ToList();

        return View(events);

    }

    // Get: <port>/events/add
    [HttpGet]
    public IActionResult Add()
    {
        List<EventCategory> categories = context.Categories.ToList();
        AddEventViewModel addEventViewModel = new AddEventViewModel(categories);
        return View( addEventViewModel);
        
    }

    [HttpPost]
    [Route("/Events/Add")]
    public IActionResult NewEvent(AddEventViewModel addEventViewModel)
    {
        if(ModelState.IsValid)
        {
            EventCategory theCategory = context.Categories.Find(addEventViewModel.CategoryId);
            Event newEvent= new Event
            {
                Name = addEventViewModel.Name,
                Description = addEventViewModel.Description,
                Category = theCategory
            }; 
            
            context.Events.Add(newEvent);
            context.SaveChanges();

            return Redirect("/Events");
        }
        return View(addEventViewModel);
    }

    [HttpGet]
    public IActionResult Delete()
    {
        ViewBag.events =context.Events.ToList();
        return View();
    }

    [HttpPost]
    public IActionResult Delete(int[] eventIds)
    {
        foreach (int eventId in eventIds)
        {
            
            Event? theEvent = context.Events.Find(eventId);
            
            if(theEvent!=null)
            {
            context.Events.Remove(theEvent);
            }
        }

        context.SaveChanges();

        return Redirect("/Events");
    }

    // [HttpPost]
    // [Route("/event/edit/{eventId}")]
    // public IActionResult Edit (int eventId)
    // {
    //    Event editEvent = EventData.GetById(eventId);
    //    ViewBag.eventToEdit = editEvent;
    //    ViewBag.title = "Edit Event "+ editEvent.Name + "(id = "+editEvent.Id + ")";

    //     return View();
    // }
    [HttpGet]
  
    public IActionResult Detail(int id)
    {
        Event theEvent = context.Events
        .Include(e => e.Category)
        .Include(e => e.Tags)
        .SingleOrDefault(e => e.Id == id);
 
    if (theEvent == null)
    {
        return NotFound(); 
    }

    EventDetailViewModel viewModel = new EventDetailViewModel(theEvent);
    return View(viewModel);
    }


}

Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coding_Events.Data;
using Coding_Events.Models;
using Coding_Events.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CodingEvents.Controllers
{
    public class TagController : Controller
    {
        private EventDbContext context;

        public TagController(EventDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Tag> tags = context.Tags.ToList();
            return View(tags);
        }

        public IActionResult Add()
        {
            Tag tag = new Tag();
            return View(tag);
        }

        [HttpPost]
        public IActionResult Add(Tag tag)
        {
            if (ModelState.IsValid)
            {
                context.Tags.Add(tag);
                context.SaveChanges();
                return Redirect("/Tag/");
            }

            return View("Add", tag);
        }


        // responds to URLs like /Tag/AddEvent/5 (where 5 is an event ID)
        public IActionResult AddEvent(int id)
        {
            Event theEvent = context.Events.Find(id);
            List<Tag> possibleTags = context.Tags.ToList();

            AddEventTagViewModel viewModel = new AddEventTagViewModel(theEvent, possibleTags);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddEvent(AddEventTagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                            int eventId = viewModel.EventId;
            int tagId = viewModel.TagId;

            Event theEvent = context.Events.Include(e => e.Tags).Where(e => e.Id == eventId).First();
            Tag theTag = context.Tags.Where(t => t.Id == tagId).First();

            theEvent.Tags.Add(theTag);

            context.SaveChanges();

            return Redirect("/Events/Detail/" + eventId);
            }
            return View(viewModel);
        }
    }
}

Views/Events/Add.cshtml
@using Coding_Events.ViewModels;
@model AddEventViewModel;

<h1>Add Event</h1>

<form asp-controller="Events" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name">
            Name
            <input type="text" name="name" />
        </label>
        <span asp-validation-for="Name" class= "text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">
            Description
            <input type="text" name="description" />
        </label>
        <span asp-validation-for="Description"></span>
    </div>
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="Model.Categories"></select>
    </div>
    <input type="submit" value="Add Event" />
</form>

Views/Events/Delete.cshtml
@{}
   <h1>Delete Event</h1>

   <form method="post">
      @foreach (var evt in ViewBag.events)
      {
         <div class="form-group">
               <label>
                  <span>@evt.Name</span>
                  <input type="checkbox" name="eventIds" value="@evt.Id" class="form-control">
               </label>
         </div>
      }

      <input type="submit" value="Delete Selected Events" class="btn btn-danger">

   </form>

Views/Events/Detail.cshtml
@model Coding_Events.ViewModels.EventDetailViewModel

<h1>@Model.Name</h1>

<table class="table">
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
    <tr>
   <th>Tags</th>
        <td>@Model.TagText</td>
        </tr>
    <tr>
        <th>Category</th>
        <td>@Model.CategoryName</td>
    </tr>
</table>

<a asp-controller="Tag" asp-action="AddEvent" asp-route-id="@Model.EventId">Add Tag</a>

Views/Events/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Edit Event</h1>

<form method="post" action="/events/edit">
    <div class="form-group">
        <label>
            Name
            <input type="text" name="name" value="@ViewBag.eventToEdit.Name"/>
        </label>
        <label>
            Description
            <input type="text" name="description" value="@ViewBag.eventToEdit.Description"/>
        </label>
           <input type="hidden" value="@ViewBag.eventToEdit.Id" name="eventId" />
    </div>
    <input type="submit" value="Edit Event" />
</form>

Views/Events/Index.cshtml
@using Coding_Events.Models
@model List<Event>

<h1>Coding Events</h1>

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>

<p>
    <a asp-controller="Events" asp-action="Delete">Delete Event</a>
</p>

@if (Model.Count == 0)
{
    <p>No events yet!</p>
}
else
{
    <table class="table">
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Category
            </th>
        </tr>
        @foreach (var evt in Model)
        {
            <tr>
                <td>@evt.Id</td>
                <td>@evt.Name</td>
                <td>@evt.Description </td>
                <td>@evt.Category.Name</td>
            </tr>
        }
    </table>
}
