Controllers/EventCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Coding_Events.Models;
using Coding_Events.Data;
using Coding_Events.ViewModels;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Coding_Events;

public class EventCategoryController : Controller
{
    private EventDbContext context;

    public EventCategoryController(EventDbContext dbContext)
    {
        
        context = dbContext;
    }

    [HttpGet]
    public IActionResult Index()
    {
        List<EventCategory> categories = context.Categories.ToList();
        return View(categories);
    }

    [HttpGet]
    public IActionResult Create()
    {
        AddEventCategoryViewModel addEventCategoryViewModel= new();
        return View(addEventCategoryViewModel);
    }

    [HttpPost("/createCategory")]
    public IActionResult ProcessCreateEventCategoryForm(AddEventCategoryViewModel addEventCategoryViewModel)
    {
        if(ModelState.IsValid)
        {
            EventCategory newEventCategory = new EventCategory
            {
                Name = addEventCategoryViewModel.Name
            };
            context.Categories.Add(newEventCategory);
            context.SaveChanges();

            return Redirect("/eventcategory/Index");
        }
        return View("Create",addEventCategoryViewModel);
    }
}

Controllers/EventsController.cs
namespace Coding_Events;
using Microsoft.AspNetCore.Mvc;
using Coding_Events.Data;
using Coding_Events.Models;
using Coding_Events.ViewModels;
using Microsoft.EntityFrameworkCore;

public class EventsController : Controller
{
    private EventDbContext context;

    public EventsController(EventDbContext dbContext)
    {
        context = dbContext;
    }


    // GET: <port>/events
    [HttpGet]
    public IActionResult Index() 
    {
        List<Event> events = context.Events.Include(e=>e.Category).ToList();

        return View(events);

    }

    // Get: <port>/events/add
    [HttpGet]
    public IActionResult Add()
    {
        List<EventCategory> categories = context.Categories.ToList();
        AddEventViewModel addEventViewModel = new AddEventViewModel(categories);
        return View( addEventViewModel);
        
    }

    [HttpPost]
    [Route("/Events/Add")]
    public IActionResult NewEvent(AddEventViewModel addEventViewModel)
    {
        if(ModelState.IsValid)
        {
            EventCategory theCategory = context.Categories.Find(addEventViewModel.CategoryId);
            Event newEvent= new Event
            {
                Name = addEventViewModel.Name,
                Description = addEventViewModel.Description,
                Category = theCategory
            }; 
            
            context.Events.Add(newEvent);
            context.SaveChanges();

            return Redirect("/Events");
        }
        return View(addEventViewModel);
    }

    [HttpGet]
    public IActionResult Delete()
    {
        ViewBag.events =context.Events.ToList();
        return View();
    }

    [HttpPost]
    public IActionResult Delete(int[] eventIds)
    {
        foreach (int eventId in eventIds)
        {
            
            Event? theEvent = context.Events.Find(eventId);
            
            if(theEvent!=null)
            {
            context.Events.Remove(theEvent);
            }
        }

        context.SaveChanges();

        return Redirect("/Events");
    }

    // [HttpPost]
    // [Route("/event/edit/{eventId}")]
    // public IActionResult Edit (int eventId)
    // {
    //    Event editEvent = EventData.GetById(eventId);
    //    ViewBag.eventToEdit = editEvent;
    //    ViewBag.title = "Edit Event "+ editEvent.Name + "(id = "+editEvent.Id + ")";

    //     return View();
    // }
    [HttpGet]
  
    public IActionResult Detail(int id)
    {
        Event theEvent = context.Events
        .Include(e => e.Category)
        .Include(e => e.Tags)
        .SingleOrDefault(e => e.Id == id);
 
    if (theEvent == null)
    {
        return NotFound(); 
    }

    EventDetailViewModel viewModel = new EventDetailViewModel(theEvent);
    return View(viewModel);
    }


}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Coding_Events</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Coding_Events.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Coding_Events</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Add">Add New Event</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">View All Events</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Create">Add New Category</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Index">View All Categories</a>
                    </ul>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Coding_Events - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>